# Generated by Django 3.1.3 on 2021-03-06 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[], max_length=100)),
                ('main_contact', models.EmailField(blank=True, max_length=254)),
                ('card_id', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[], default='INIT', max_length=100)),
                ('last_activity', models.DateField(default=datetime.date.today)),
                ('comments_number', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Prospector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_contractor', models.BooleanField(default=False)),
                ('is_postseller', models.BooleanField(default=False)),
                ('list_id_sales', models.CharField(max_length=100, null=True)),
                ('list_id_contracts', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('date_closed', models.DateField(default=datetime.date.today)),
                ('intake', models.PositiveIntegerField()),
                ('payday', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[], max_length=100)),
                ('fee_type', models.CharField(choices=[], max_length=100)),
                ('payment_form', models.CharField(blank=True, choices=[], max_length=100)),
                ('needs_receipt', models.BooleanField(default=False)),
                ('stand_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stand_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_stand', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('activities', models.ManyToManyField(to='prospection.Activity')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospection.company')),
                ('contractor', models.ForeignKey(blank=True, limit_choices_to={'is_contractor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_contracts', related_query_name='contractor_contract', to='prospection.prospector')),
                ('postseller', models.ForeignKey(blank=True, limit_choices_to={'is_postseller': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posteller_contracts', related_query_name='posteller_contract', to='prospection.prospector')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='prospector',
            field=models.ForeignKey(limit_choices_to={'is_seller': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', related_query_name='company', to='prospection.prospector'),
        ),
        migrations.AddField(
            model_name='activity',
            name='prospector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospection.prospector'),
        ),
    ]
