# Generated by Django 3.1.3 on 2021-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, choices=[('G', 'generic')], max_length=100),
        ),
    ]
